// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package streamingimporter.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the StreamingImporter module

	/**
	* This is a special mapping value for items where you want to specify the Excel row number.
	*/
	public static java.lang.String getFILL_LINE_NUMBER()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("StreamingImporter.FILL_LINE_NUMBER");
	}
}