// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("cbc7c5ae-bfa2-414d-9eb4-4f3bd55e42e1"),
	low("1c1df28d-70dd-4a9d-a2b0-1062abb0ff64"),
	medium("5c8f7952-86cb-4923-b46b-a57f66585e9c"),
	high("0703a7f0-67c4-41f8-8358-1b0d01e3d407"),
	custom("4215f043-fe88-4a91-9ef5-be19696ccf20");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
