// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package streamingimporter.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the StreamingImporter module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cB_emptyBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("StreamingImporter.CB_empty");
		return builder;
	}

	public static void cB_empty(IContext context)
	{
		cB_emptyBuilder().execute(context);
	}
}
