// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("7b21a4b6-8b70-4435-9121-16c8936037bf"),
	English("bfdd1130-ffda-406c-a711-40275848690c"),
	French("dd7f1525-6a3d-45ca-a2ee-d5a0577ad951"),
	German("4b374ccf-df02-4fb9-869c-9c030cd37f37"),
	Hindi("0506846b-d3c6-46f1-ab2f-32f3d27f8148"),
	Portuguese("86eef23b-3ad3-4d79-9f92-0228ef2f7484"),
	Spanish("b89dbb0f-d072-4d59-b362-17c505d3cded"),
	Turkish("e33db8c0-85e5-40c6-a9be-8f55c8453f76");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
