// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package streamingimporter.proxies;

public class SampleImportWork implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sampleImportWorkMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "StreamingImporter.SampleImportWork";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ValidationResults("ValidationResults"),
		LineNumber("LineNumber"),
		EmpID("EmpID"),
		EmpName("EmpName"),
		EmpDept("EmpDept"),
		Amount("Amount"),
		Note("Note"),
		ImportDateTime("ImportDateTime"),
		IsValid("IsValid"),
		SampleImportWork_SampleImportFile("StreamingImporter.SampleImportWork_SampleImportFile");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SampleImportWork(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SampleImportWork(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sampleImportWorkMendixObject)
	{
		if (sampleImportWorkMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!sampleImportWorkMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sampleImportWorkMendixObject = sampleImportWorkMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static streamingimporter.proxies.SampleImportWork initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new streamingimporter.proxies.SampleImportWork(context, mendixObject);
	}

	public static streamingimporter.proxies.SampleImportWork load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return streamingimporter.proxies.SampleImportWork.initialize(context, mendixObject);
	}

	public static java.util.List<streamingimporter.proxies.SampleImportWork> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> streamingimporter.proxies.SampleImportWork.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ValidationResults
	 */
	public final java.lang.String getValidationResults()
	{
		return getValidationResults(getContext());
	}

	/**
	 * @param context
	 * @return value of ValidationResults
	 */
	public final java.lang.String getValidationResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ValidationResults.toString());
	}

	/**
	 * Set value of ValidationResults
	 * @param validationresults
	 */
	public final void setValidationResults(java.lang.String validationresults)
	{
		setValidationResults(getContext(), validationresults);
	}

	/**
	 * Set value of ValidationResults
	 * @param context
	 * @param validationresults
	 */
	public final void setValidationResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String validationresults)
	{
		getMendixObject().setValue(context, MemberNames.ValidationResults.toString(), validationresults);
	}

	/**
	 * @return value of LineNumber
	 */
	public final java.lang.String getLineNumber()
	{
		return getLineNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of LineNumber
	 */
	public final java.lang.String getLineNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LineNumber.toString());
	}

	/**
	 * Set value of LineNumber
	 * @param linenumber
	 */
	public final void setLineNumber(java.lang.String linenumber)
	{
		setLineNumber(getContext(), linenumber);
	}

	/**
	 * Set value of LineNumber
	 * @param context
	 * @param linenumber
	 */
	public final void setLineNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String linenumber)
	{
		getMendixObject().setValue(context, MemberNames.LineNumber.toString(), linenumber);
	}

	/**
	 * @return value of EmpID
	 */
	public final java.lang.String getEmpID()
	{
		return getEmpID(getContext());
	}

	/**
	 * @param context
	 * @return value of EmpID
	 */
	public final java.lang.String getEmpID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmpID.toString());
	}

	/**
	 * Set value of EmpID
	 * @param empid
	 */
	public final void setEmpID(java.lang.String empid)
	{
		setEmpID(getContext(), empid);
	}

	/**
	 * Set value of EmpID
	 * @param context
	 * @param empid
	 */
	public final void setEmpID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String empid)
	{
		getMendixObject().setValue(context, MemberNames.EmpID.toString(), empid);
	}

	/**
	 * @return value of EmpName
	 */
	public final java.lang.String getEmpName()
	{
		return getEmpName(getContext());
	}

	/**
	 * @param context
	 * @return value of EmpName
	 */
	public final java.lang.String getEmpName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmpName.toString());
	}

	/**
	 * Set value of EmpName
	 * @param empname
	 */
	public final void setEmpName(java.lang.String empname)
	{
		setEmpName(getContext(), empname);
	}

	/**
	 * Set value of EmpName
	 * @param context
	 * @param empname
	 */
	public final void setEmpName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String empname)
	{
		getMendixObject().setValue(context, MemberNames.EmpName.toString(), empname);
	}

	/**
	 * @return value of EmpDept
	 */
	public final java.lang.String getEmpDept()
	{
		return getEmpDept(getContext());
	}

	/**
	 * @param context
	 * @return value of EmpDept
	 */
	public final java.lang.String getEmpDept(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmpDept.toString());
	}

	/**
	 * Set value of EmpDept
	 * @param empdept
	 */
	public final void setEmpDept(java.lang.String empdept)
	{
		setEmpDept(getContext(), empdept);
	}

	/**
	 * Set value of EmpDept
	 * @param context
	 * @param empdept
	 */
	public final void setEmpDept(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String empdept)
	{
		getMendixObject().setValue(context, MemberNames.EmpDept.toString(), empdept);
	}

	/**
	 * @return value of Amount
	 */
	public final java.lang.String getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.lang.String getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.lang.String amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * @return value of Note
	 */
	public final java.lang.String getNote()
	{
		return getNote(getContext());
	}

	/**
	 * @param context
	 * @return value of Note
	 */
	public final java.lang.String getNote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Note.toString());
	}

	/**
	 * Set value of Note
	 * @param note
	 */
	public final void setNote(java.lang.String note)
	{
		setNote(getContext(), note);
	}

	/**
	 * Set value of Note
	 * @param context
	 * @param note
	 */
	public final void setNote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String note)
	{
		getMendixObject().setValue(context, MemberNames.Note.toString(), note);
	}

	/**
	 * @return value of ImportDateTime
	 */
	public final java.util.Date getImportDateTime()
	{
		return getImportDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportDateTime
	 */
	public final java.util.Date getImportDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ImportDateTime.toString());
	}

	/**
	 * Set value of ImportDateTime
	 * @param importdatetime
	 */
	public final void setImportDateTime(java.util.Date importdatetime)
	{
		setImportDateTime(getContext(), importdatetime);
	}

	/**
	 * Set value of ImportDateTime
	 * @param context
	 * @param importdatetime
	 */
	public final void setImportDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date importdatetime)
	{
		getMendixObject().setValue(context, MemberNames.ImportDateTime.toString(), importdatetime);
	}

	/**
	 * @return value of IsValid
	 */
	public final java.lang.Boolean getIsValid()
	{
		return getIsValid(getContext());
	}

	/**
	 * @param context
	 * @return value of IsValid
	 */
	public final java.lang.Boolean getIsValid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsValid.toString());
	}

	/**
	 * Set value of IsValid
	 * @param isvalid
	 */
	public final void setIsValid(java.lang.Boolean isvalid)
	{
		setIsValid(getContext(), isvalid);
	}

	/**
	 * Set value of IsValid
	 * @param context
	 * @param isvalid
	 */
	public final void setIsValid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isvalid)
	{
		getMendixObject().setValue(context, MemberNames.IsValid.toString(), isvalid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SampleImportWork_SampleImportFile
	 */
	public final streamingimporter.proxies.SampleImportFile getSampleImportWork_SampleImportFile() throws com.mendix.core.CoreException
	{
		return getSampleImportWork_SampleImportFile(getContext());
	}

	/**
	 * @param context
	 * @return value of SampleImportWork_SampleImportFile
	 * @throws com.mendix.core.CoreException
	 */
	public final streamingimporter.proxies.SampleImportFile getSampleImportWork_SampleImportFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		streamingimporter.proxies.SampleImportFile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SampleImportWork_SampleImportFile.toString());
		if (identifier != null) {
			result = streamingimporter.proxies.SampleImportFile.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SampleImportWork_SampleImportFile
	 * @param sampleimportwork_sampleimportfile
	 */
	public final void setSampleImportWork_SampleImportFile(streamingimporter.proxies.SampleImportFile sampleimportwork_sampleimportfile)
	{
		setSampleImportWork_SampleImportFile(getContext(), sampleimportwork_sampleimportfile);
	}

	/**
	 * Set value of SampleImportWork_SampleImportFile
	 * @param context
	 * @param sampleimportwork_sampleimportfile
	 */
	public final void setSampleImportWork_SampleImportFile(com.mendix.systemwideinterfaces.core.IContext context, streamingimporter.proxies.SampleImportFile sampleimportwork_sampleimportfile)
	{
		if (sampleimportwork_sampleimportfile == null) {
			getMendixObject().setValue(context, MemberNames.SampleImportWork_SampleImportFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SampleImportWork_SampleImportFile.toString(), sampleimportwork_sampleimportfile.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sampleImportWorkMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final streamingimporter.proxies.SampleImportWork that = (streamingimporter.proxies.SampleImportWork) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
