// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package streamingimporter.proxies;

public class SampleImportFile extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "StreamingImporter.SampleImportFile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ImportStartDateTime("ImportStartDateTime"),
		ImportFinishDateTime("ImportFinishDateTime"),
		ImportedCount("ImportedCount"),
		ErrorRecordCount("ErrorRecordCount"),
		ElapsedSeconds("ElapsedSeconds"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SampleImportFile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SampleImportFile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sampleImportFileMendixObject)
	{
		super(context, sampleImportFileMendixObject);
		if (!sampleImportFileMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static streamingimporter.proxies.SampleImportFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new streamingimporter.proxies.SampleImportFile(context, mendixObject);
	}

	public static streamingimporter.proxies.SampleImportFile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return streamingimporter.proxies.SampleImportFile.initialize(context, mendixObject);
	}

	public static java.util.List<streamingimporter.proxies.SampleImportFile> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> streamingimporter.proxies.SampleImportFile.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ImportStartDateTime
	 */
	public final java.util.Date getImportStartDateTime()
	{
		return getImportStartDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportStartDateTime
	 */
	public final java.util.Date getImportStartDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ImportStartDateTime.toString());
	}

	/**
	 * Set value of ImportStartDateTime
	 * @param importstartdatetime
	 */
	public final void setImportStartDateTime(java.util.Date importstartdatetime)
	{
		setImportStartDateTime(getContext(), importstartdatetime);
	}

	/**
	 * Set value of ImportStartDateTime
	 * @param context
	 * @param importstartdatetime
	 */
	public final void setImportStartDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date importstartdatetime)
	{
		getMendixObject().setValue(context, MemberNames.ImportStartDateTime.toString(), importstartdatetime);
	}

	/**
	 * @return value of ImportFinishDateTime
	 */
	public final java.util.Date getImportFinishDateTime()
	{
		return getImportFinishDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportFinishDateTime
	 */
	public final java.util.Date getImportFinishDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ImportFinishDateTime.toString());
	}

	/**
	 * Set value of ImportFinishDateTime
	 * @param importfinishdatetime
	 */
	public final void setImportFinishDateTime(java.util.Date importfinishdatetime)
	{
		setImportFinishDateTime(getContext(), importfinishdatetime);
	}

	/**
	 * Set value of ImportFinishDateTime
	 * @param context
	 * @param importfinishdatetime
	 */
	public final void setImportFinishDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date importfinishdatetime)
	{
		getMendixObject().setValue(context, MemberNames.ImportFinishDateTime.toString(), importfinishdatetime);
	}

	/**
	 * @return value of ImportedCount
	 */
	public final java.lang.Integer getImportedCount()
	{
		return getImportedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportedCount
	 */
	public final java.lang.Integer getImportedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ImportedCount.toString());
	}

	/**
	 * Set value of ImportedCount
	 * @param importedcount
	 */
	public final void setImportedCount(java.lang.Integer importedcount)
	{
		setImportedCount(getContext(), importedcount);
	}

	/**
	 * Set value of ImportedCount
	 * @param context
	 * @param importedcount
	 */
	public final void setImportedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer importedcount)
	{
		getMendixObject().setValue(context, MemberNames.ImportedCount.toString(), importedcount);
	}

	/**
	 * @return value of ErrorRecordCount
	 */
	public final java.lang.Integer getErrorRecordCount()
	{
		return getErrorRecordCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorRecordCount
	 */
	public final java.lang.Integer getErrorRecordCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ErrorRecordCount.toString());
	}

	/**
	 * Set value of ErrorRecordCount
	 * @param errorrecordcount
	 */
	public final void setErrorRecordCount(java.lang.Integer errorrecordcount)
	{
		setErrorRecordCount(getContext(), errorrecordcount);
	}

	/**
	 * Set value of ErrorRecordCount
	 * @param context
	 * @param errorrecordcount
	 */
	public final void setErrorRecordCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer errorrecordcount)
	{
		getMendixObject().setValue(context, MemberNames.ErrorRecordCount.toString(), errorrecordcount);
	}

	/**
	 * @return value of ElapsedSeconds
	 */
	public final java.math.BigDecimal getElapsedSeconds()
	{
		return getElapsedSeconds(getContext());
	}

	/**
	 * @param context
	 * @return value of ElapsedSeconds
	 */
	public final java.math.BigDecimal getElapsedSeconds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ElapsedSeconds.toString());
	}

	/**
	 * Set value of ElapsedSeconds
	 * @param elapsedseconds
	 */
	public final void setElapsedSeconds(java.math.BigDecimal elapsedseconds)
	{
		setElapsedSeconds(getContext(), elapsedseconds);
	}

	/**
	 * Set value of ElapsedSeconds
	 * @param context
	 * @param elapsedseconds
	 */
	public final void setElapsedSeconds(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal elapsedseconds)
	{
		getMendixObject().setValue(context, MemberNames.ElapsedSeconds.toString(), elapsedseconds);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final streamingimporter.proxies.SampleImportFile that = (streamingimporter.proxies.SampleImportFile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
