// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package streamingimporter.actions;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive.PrimitiveType;

import streamingimporter.mplementation.XssfExcelReader;
import streamingimporter.proxies.constants.Constants;

public class StreamingImportFromXlsx extends UserAction<java.lang.Long> {
	/** @deprecated use xlsxFileDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __xlsxFileDocument;
	private final system.proxies.FileDocument xlsxFileDocument;
	private final java.lang.String destinationEntity;
	private final java.lang.String sheetName;
	private final java.lang.Long headerLineNumber;
	private final java.lang.Long skipCount;
	private final IMendixObject columnNameMapping;
	private final java.lang.Long batchCommitSize;
	private final java.lang.Long transactionChunkSize;
	private final java.lang.String beforeBachCommitCallBackMicroflow;
	private final java.util.List<IMendixObject> importedObjects;
	private final java.lang.Boolean useSystemContext;

	public StreamingImportFromXlsx(
			IContext context,
			IMendixObject _xlsxFileDocument,
			java.lang.String _destinationEntity,
			java.lang.String _sheetName,
			java.lang.Long _headerLineNumber,
			java.lang.Long _skipCount,
			IMendixObject _columnNameMapping,
			java.lang.Long _batchCommitSize,
			java.lang.Long _transactionChunkSize,
			java.lang.String _beforeBachCommitCallBackMicroflow,
			java.util.List<IMendixObject> _importedObjects,
			java.lang.Boolean _useSystemContext) {
		super(context);
		this.__xlsxFileDocument = _xlsxFileDocument;
		this.xlsxFileDocument = _xlsxFileDocument == null ? null
				: system.proxies.FileDocument.initialize(getContext(), _xlsxFileDocument);
		this.destinationEntity = _destinationEntity;
		this.sheetName = _sheetName;
		this.headerLineNumber = _headerLineNumber;
		this.skipCount = _skipCount;
		this.columnNameMapping = _columnNameMapping;
		this.batchCommitSize = _batchCommitSize;
		this.transactionChunkSize = _transactionChunkSize;
		this.beforeBachCommitCallBackMicroflow = _beforeBachCommitCallBackMicroflow;
		this.importedObjects = _importedObjects;
		this.useSystemContext = _useSystemContext;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception {
		// BEGIN USER CODE
		if (this.xlsxFileDocument == null) {
			throw new IllegalArgumentException("xlsxFileDocument cannot be null");
		}

		IContext workingContext = (Boolean.TRUE.equals(this.useSystemContext))
				? Core.createSystemContext()
				: getContext();

		long headerLine = (this.headerLineNumber != null && this.headerLineNumber > 0) ? this.headerLineNumber : 1L;
		long skip = (this.skipCount != null && this.skipCount >= 0) ? this.skipCount : 1L;
		long batchSize = (this.batchCommitSize != null && this.batchCommitSize > 0) ? this.batchCommitSize : 100L;
		long txChunkSize = (this.transactionChunkSize != null && this.transactionChunkSize > 0)
				? this.transactionChunkSize
				: 0L;

		// 対象エンティティのメタ情報取得
		IMetaObject metaObject = Core.getMetaObject(this.destinationEntity);
		if (metaObject == null) {
			throw new CoreException("Destination entity type not found: " + this.destinationEntity);
		}

		// FileDocument自動関連付け用の属性/アソシエーションの探索
		String fileDocAssociationName = findFileDocumentAssociation(metaObject);

		// バッチ処理用コンテキスト
		ImportRowProcessor processor = new ImportRowProcessor(
				workingContext,
				metaObject,
				this.columnNameMapping,
				this.xlsxFileDocument.getMendixObject(),
				fileDocAssociationName,
				headerLine,
				skip,
				batchSize,
				txChunkSize,
				this.beforeBachCommitCallBackMicroflow,
				this.importedObjects);

		try (InputStream is = Core.getFileDocumentContent(workingContext, this.xlsxFileDocument.getMendixObject())) {
			// シート名指定（未指定・空文字の場合は null を渡して1番目のシートを読み込み）
			String targetSheet = (this.sheetName != null && !this.sheetName.trim().isEmpty())
					? this.sheetName.trim()
					: null;

			XssfExcelReader.read(is, targetSheet, processor);
		}
		// 残ったバッチの処理・コミット
		processor.flushBatch();

		return processor.getProcessedCount();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString() {
		return "StreamingImportFromXlsx";
	}

	// BEGIN EXTRA CODE
	public static final ILogNode logger = Core.getLogger("StreamingImporter");

	/**
	 * FileDocumentへのアソシエーション（またはそのサブクラス）を自動検索
	 */
	private String findFileDocumentAssociation(IMetaObject targetMeta) {
		for (var assoc : targetMeta.getMetaAssociationsParent()) {
			IMetaObject child = assoc.getChild();
			if (child != null && isFileDocumentOrSubclass(child)) {
				return assoc.getName();
			}
		}
		return null;
	}

	private boolean isFileDocumentOrSubclass(IMetaObject meta) {
		if ("System.FileDocument".equals(meta.getName()))
			return true;
		IMetaObject superMeta = meta.getSuperObject();
		return superMeta != null && isFileDocumentOrSubclass(superMeta);
	}

	/**
	 * 行処理プロセッサ (XssfExcelReader.RowProcessor の実装)
	 */
	private static class ImportRowProcessor implements XssfExcelReader.RowProcessor {
		private final IContext context;
		private final IMetaObject targetMeta;
		private final IMendixObject mappingObj;
		private final IMendixObject fileDocObj;
		private final String fileDocAssocName;
		private final long headerLineNumber;
		private final long skipCount;
		private final long batchSize;
		private final long txChunkSize;
		private final String callbackMicroflow;
		private final List<IMendixObject> importedObjectsOutput;

		private final Map<String, String> headerColumnMap = new HashMap<>(); // colKey -> HeaderName
		private final Map<String, String> attrToColMap = new HashMap<>(); // attrName -> colKey
		private final List<IMendixObject> currentBatch = new ArrayList<>();

		private long processedCount = 0;
		private long txProcessedCount = 0;

		public ImportRowProcessor(IContext context, IMetaObject targetMeta, IMendixObject mappingObj,
				IMendixObject fileDocObj, String fileDocAssocName,
				long headerLineNumber, long skipCount, long batchSize,
				long txChunkSize, String callbackMicroflow,
				List<IMendixObject> importedObjectsOutput) {
			this.context = context;
			this.targetMeta = targetMeta;
			this.mappingObj = mappingObj;
			this.fileDocObj = fileDocObj;
			this.fileDocAssocName = fileDocAssocName;
			this.headerLineNumber = headerLineNumber;
			this.skipCount = skipCount;
			this.batchSize = batchSize;
			this.txChunkSize = txChunkSize;
			this.callbackMicroflow = callbackMicroflow;
			this.importedObjectsOutput = importedObjectsOutput;
		}

		@Override
		public void processRow(int rowIndex, Map<String, String> rowData) throws Exception {
			// XssfExcelReader の rowIndex は0ベース（0, 1, 2...）か1ベースかを補正
			// パラメータの headerLineNumber, skipCount (1ベース) と合わせるため +1 して比較
			long currentLine = rowIndex + 1L;

			// 1. ヘッダー行の解析
			if (currentLine == this.headerLineNumber) {
				this.headerColumnMap.putAll(rowData);
				buildAttributeMapping();
				return;
			}

			// スキップ行の無視
			if (currentLine <= this.skipCount) {
				return;
			}

			// 2. データ行の処理
			IMendixObject newObj = Core.instantiate(context, targetMeta.getName());

			// 列の値をEntityの属性にセット
			for (Map.Entry<String, String> entry : attrToColMap.entrySet()) {
				String attrName = entry.getKey();
				String colKey = entry.getValue();

				if (Constants.getFILL_LINE_NUMBER().equals(colKey)) {
					// 行番号を文字列化してセット (1ベースの行番号)
					newObj.setValue(context, attrName, String.valueOf(currentLine));
				} else {
					String cellValue = rowData.get(colKey);
					if (cellValue != null) {
						newObj.setValue(context, attrName, cellValue);
					}
				}
			}

			// FileDocument アソシエーションの自動設定
			if (fileDocAssocName != null && fileDocObj != null) {
				newObj.setValue(context, fileDocAssocName, fileDocObj.getId());
			}

			currentBatch.add(newObj);
			if (importedObjectsOutput != null) {
				importedObjectsOutput.add(newObj);
			}

			processedCount++;
			txProcessedCount++;

			// バッチサイズに達したらコミット処理
			if (currentBatch.size() >= batchSize) {
				flushBatch();
			}

			// トランザクション分割（指定がある場合）
			if (txChunkSize > 0 && txProcessedCount >= txChunkSize) {
				if (context.isInTransaction()) {
					context.endTransaction();
					context.startTransaction();
					if (logger.isDebugEnabled()) {
						logger.debug("Transaction chunk committed after processing " + txProcessedCount + " rows.");
					}
				}
				txProcessedCount = 0;
			}
		}

		/**
		 * マッピング定義の構築 (属性名 <-> Excel列キー)
		 */
		private void buildAttributeMapping() {
			attrToColMap.clear();

			// 対象エンティティの String 型属性のみを取得
			List<IMetaPrimitive> primitives = new ArrayList<>();
			for (IMetaPrimitive p : targetMeta.getMetaPrimitives()) {
				if (!p.isVirtual() && p.getType() == PrimitiveType.String) {
					primitives.add(p);
				}
			}

			if (mappingObj != null) {
				// パターンA: columnNameMapping が指定されている場合
				for (IMetaPrimitive p : primitives) {
					String attrName = p.getName();
					String mappedValue = mappingObj.getValue(context, attrName);

					if (mappedValue != null && !mappedValue.trim().isEmpty()) {
						String cleanValue = mappedValue.trim();
						String colKey = parseColumnKeyOrHeader(cleanValue);
						if (colKey != null) {
							attrToColMap.put(attrName, colKey);
						}
					}
				}
			} else {
				// パターンB: columnNameMapping が empty の場合（出現順に割り当て）
				// headerColumnMap のキー("A", "B", "AA"...)を列順(0, 1, 2...)にソート
				List<String> sortedColKeys = new ArrayList<>(headerColumnMap.keySet());
				sortedColKeys.sort(Comparator.comparingInt(this::excelColumnToIdx));

				for (int i = 0; i < primitives.size() && i < sortedColKeys.size(); i++) {
					attrToColMap.put(primitives.get(i).getName(), sortedColKeys.get(i));
				}
			}
		}

		/**
		 * ヘッダー名、列記号($A, $B...)、または列番号($1, $2...)から colKey を判定
		 */
		private String parseColumnKeyOrHeader(String targetStr) {
			String clean = targetStr.trim();

			// 特殊キーワード: 行番号
			if (Constants.getFILL_LINE_NUMBER().equalsIgnoreCase(clean)) {
				return Constants.getFILL_LINE_NUMBER();
			}

			// 1. '$' が明示的に付いている場合 ($1, $A) -> 無条件で列指定
			if (clean.startsWith("$")) {
				String sub = clean.substring(1).trim();
				if (sub.matches("(?i)^[A-Z]+$"))
					return sub.toUpperCase();
				if (sub.matches("^\\d+$"))
					return idxToExcelColumn(Integer.parseInt(sub) - 1);
			}

			// 2. まずヘッダー行の文字列と完全一致するかチェック（"氏名" や "1月" など）
			for (Map.Entry<String, String> entry : headerColumnMap.entrySet()) {
				if (clean.equalsIgnoreCase(entry.getValue())) {
					return entry.getKey(); // ヘッダーで見つかればその列キーを返す
				}
			}

			// 3. ヘッダーになかった場合で、"A", "B" などの列記号っぽい場合
			if (clean.matches("(?i)^[A-Z]+$")) {
				return clean.toUpperCase();
			}

			// 4. ヘッダーになかった場合で、"1", "2" などの数字の場合（1ベース）
			if (clean.matches("^\\d+$")) {
				int oneBasedIdx = Integer.parseInt(clean);
				if (oneBasedIdx > 0) {
					return idxToExcelColumn(oneBasedIdx - 1);
				}
			}

			return null;
		}

		/**
		 * 0ベースインデックスを Excel列記号に変換 (0 -> "A", 1 -> "B", 25 -> "Z", 26 -> "AA")
		 */
		private String idxToExcelColumn(int index) {
			StringBuilder sb = new StringBuilder();
			while (index >= 0) {
				sb.insert(0, (char) ('A' + (index % 26)));
				index = (index / 26) - 1;
			}
			return sb.toString();
		}

		private int excelColumnToIdx(String col) {
			int result = 0;
			for (int i = 0; i < col.length(); i++) {
				result = result * 26 + (col.charAt(i) - 'A' + 1);
			}
			return result - 1; // 0ベースインデックス
		}

		public void flushBatch() throws Exception {
			if (currentBatch.isEmpty())
				return;

			// コールバック呼び出し（CB_empty 以外が指定されている場合）
			if (callbackMicroflow != null && !callbackMicroflow.contains("CB_empty")
					&& !callbackMicroflow.trim().isEmpty()) {
				try {
					Core.microflowCall(callbackMicroflow)
							.withParam("DestinationList", new ArrayList<>(currentBatch))
							.execute(context);
				} catch (Exception e) {
					throw new RuntimeException("Error executing callback microflow: " + callbackMicroflow, e);
				}
			}

			// 対象がPersistable Entityの場合のみ一括Commit
			if (targetMeta.isPersistable()) {
				Core.commit(context, currentBatch);
				if (logger.isDebugEnabled()) {
					logger.debug("Committed batch of " + currentBatch.size() + " objects to entity: "
							+ targetMeta.getName());
				}
			}

			currentBatch.clear();
		}

		public long getProcessedCount() {
			return processedCount;
		}
	}
	// END EXTRA CODE
}
