// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("0e2eeb41-6c26-4e63-a087-1e438de6c4df"),
	startsWith("094d8f0a-03ee-446c-bdfb-d7f4df97f745"),
	endsWith("3346a8ac-b5c4-4e3f-8bad-904f76b1a08a"),
	between("2c9c3682-f667-4a55-8ee9-9235a3f8ce41"),
	greater("8f5d880d-ad91-487d-a81a-2ffc819481bb"),
	greaterEqual("ba4854bd-1a49-440e-9181-3966ff2af1a6"),
	equal("1da0f11a-a164-42a5-9b72-0135b3fb0b08"),
	notEqual("46149985-54bd-4ac7-81ce-d1c53c963977"),
	smaller("57f8a432-ce4c-47d7-9a50-ab69cdf75471"),
	smallerEqual("85a2d746-ed44-4a21-acc4-64ac125926ba"),
	empty("0567fdc2-aea9-41bb-961e-2286853f9654"),
	notEmpty("15e847aa-6d1b-4ad3-9314-e4bd7f72f10e");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
